title: The Invariant
description: Thoughts on science, technology, and human nature.
url: "https://the-invariant.github.io"
baseurl: ""
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
highlighter: rouge
